#!/bin/bash -x

set -e

# Support changing environment variable options via docker run -e
ENV_FILE="/etc/ood/config/apps/shell/env"

if [ -f "$ENV_FILE" ]; then
  sudo env > $ENV_FILE
fi

export USER=$(whoami) # $USER isn't set!?

APP_DEV_DIR="$HOME/ondemand/dev"
OOD_DEV_DIR="/var/www/ood/apps/dev/$USER"

sudo su root <<MKDEV
  mkdir -p $OOD_DEV_DIR 
  cd $OOD_DEV_DIR
  ln -s $APP_DEV_DIR gateway
MKDEV

sudo chown $USER:$USER $HOME/ondemand # doesn't mount quite right

source /etc/os-release

if [ "$ID" == "centos" ]; then
  sudo /opt/rh/httpd24/root/usr/sbin/httpd-scl-wrapper -DFOREGROUND
elif [ "$ID" == "debian" ]; then
  sudo su root <<RUNAPACHE
  source /etc/apache2/envvars
  /usr/sbin/apache2 -k start
  PID=\$(pgrep apache2 | head -n 1)
  tail "--pid=\$PID" -f /dev/null
RUNAPACHE
fi
